---
- name: Install booklore
  block:
    - name: Install NFS client and mount volumes
      ansible.builtin.include_role:
        name: nfs_client
      vars:
        nfs_client_mounts:
          - { volume: booklore, path: /mnt/booklore, rights: rw }

    - name: Create app directory
      ansible.builtin.file:
        path: "{{ booklore_directory }}"
        state: directory
        mode: 0755

    - name: Create app sub-directories
      ansible.builtin.file:
        path: "{{ booklore_directory }}/{{ item }}"
        state: directory
        mode: 0755
        owner: "{{ ephemera_puid }}"
        group: "{{ ephemera_pgid }}"
      loop:
        - bookdrop
        - ephemera_data
        - ephemera_downloads

    - name: Copy docker-compose file
      ansible.builtin.template:
        src: docker-compose.yml.j2
        dest: "{{ booklore_directory }}/docker-compose.yml"
        owner: root
        group: root
        mode: 0644

    - name: Create and start app
      community.docker.docker_compose_v2:
        project_src: "{{ booklore_directory }}"
        recreate: always
        pull: missing
        remove_orphans: true
        remove_volumes: true
        state: restarted

    - name: Wait until certificate is registered
      ansible.builtin.uri:
        url: "https://{{ booklore_uri }}/"
        validate_certs: true
        status_code:
          - 200
      register: uri_output
      until: uri_output.status == 200
      delay: 10
      retries: 30       # Retries for 30 * 10 secs = 300 secs = 5 mins

  tags: booklore
