---
- name: Install glance
  block:
    - name: Create app directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      loop:
        - "{{ glance_directory }}"
        - "{{ glance_directory }}/assets"
        - "{{ glance_directory }}/config"

    - name: Copy app files
      ansible.builtin.template:
        src: "{{ item.file }}.j2"
        dest: "{{ glance_directory }}/{{ item.folder }}{{ item.file }}"
        owner: root
        group: root
        mode: 0644
      loop:
        - { file: 'docker-compose.yml', folder: '' }
        - { file: 'glance.yml', folder: 'config/' }
        - { file: 'home.yml', folder: 'config/' }
        - { file: 'user.css', folder: 'assets/' }

    - name: Create and start app
      community.docker.docker_compose_v2:
        project_src: "{{ glance_directory }}"
        recreate: always
        pull: missing
        remove_orphans: true
        remove_volumes: true
        state: restarted

    - name: Wait until certificate is registered
      ansible.builtin.uri:
        url: "https://{{ glance_uri }}/"
        validate_certs: true
        status_code:
          - 200
      register: uri_output
      until: uri_output.status == 200
      delay: 10
      retries: 30       # Retries for 30 * 10 secs = 300 secs = 5 mins

  tags: glance
