---
# Connection info used by all playbooks
ansible_user: root
ansible_ssh_private_key_file: ~/.ssh/id_ed25519

# Global values
apt_cache_time: 1800
global_domain: macminis.net
global_tz: America/New_York
dns_external_servers:
  # Cloudflare DNS
  - 1.1.1.1
  - 1.0.0.1
