---
# ? Using older version
# ? See: https://github.com/orgs/portainer/discussions/12926
hostname_in_uri: false

portainer_directory: /opt/portainer
portainer_version: 2.20.2
portainer_port: 9000

portainer_host: "{{ 'portainer' if hostname_in_uri == false else 'portainer-' + inventory_hostname_short }}"
portainer_uri: "{{ portainer_host }}.{{ global_domain }}"
