---
- name: Configure glances
  block:

    - name: Create app directories
      ansible.builtin.file:
        path: "{{ glances_directory }}"
        state: directory
        mode: 0755

    - name: Copy docker-compose file
      ansible.builtin.template:
        src: docker-compose.yml.j2
        dest: "{{ glances_directory }}/docker-compose.yml"
        owner: root
        group: root
        mode: 0644

    - name: Copy password file
      ansible.builtin.copy:
        dest: "{{ glances_directory }}/glances_password"
        content: "{{ glances_password_file_hash }}"
        owner: root
        group: root
        mode: 0600

    - name: Create and start app
      community.docker.docker_compose_v2:
        project_src: "{{ glances_directory }}"
        recreate: always
        pull: missing
        remove_orphans: true
        remove_volumes: true
        state: restarted

    - name: Wait until site is up
      ansible.builtin.uri:
        url: "https://{{ glances_uri }}/"
        validate_certs: true
        status_code:
          - 200
      register: uri_output
      until: uri_output.status == 200
      delay: 10
      retries: 12       # Retries for 12 * 10 secs = 120 secs = 2 mins

  tags: glances
