---
version: '3'

vars:
  NET_LXC_HOST: net-lxc
  NET_LXC_HOST_FQDN: "{{.NET_LXC_HOST}}.{{.DOMAIN}}"
  NET_LXC_TF_DIR: "{{.TERRAFORM_DIR}}/{{.NET_LXC_HOST}}"
  NET_LXC_ANSIBLE_PLAYBOOK: "{{.NET_LXC_HOST}}-provision.yml"

tasks:
  check:
    desc: "Check '{{.NET_LXC_HOST}}' host vars"
    dir: "{{.NET_LXC_TF_DIR}}"
    cmds:
      - "echo NET_LXC_HOST={{.NET_LXC_HOST}}"
      - "echo NET_LXC_HOST_FQDN={{.NET_LXC_HOST_FQDN}}"
      - "echo NET_LXC_TF_DIR={{.NET_LXC_TF_DIR}}"
      - "echo NET_LXC_ANSIBLE_PLAYBOOK={{.NET_LXC_ANSIBLE_PLAYBOOK}}"

  # ? Terraform
  create:
    desc: "Create '{{.NET_LXC_HOST}}' host"
    dir: "{{.NET_LXC_TF_DIR}}"
    cmds:
      - terraform init
      - terraform fmt && terraform validate
      - terraform apply

  destroy:
    desc: "Destroy '{{.NET_LXC_HOST}}' host"
    dir: "{{.NET_LXC_TF_DIR}}"
    cmds:
      - terraform destroy -compact-warnings

  update-dns:
    desc: "Update DNS records for '{{.NET_LXC_HOST}}' host"
    dir: "{{.NET_LXC_TF_DIR}}"
    cmds:
      - terraform init
      - terraform fmt && terraform validate
      - terraform apply -compact-warnings -target=module.my_lxc.cloudflare_record.cname_records

  # ? Ansible
  provision:
    desc: "Provision '{{.NET_LXC_HOST}}' via Ansible"
    dir: "{{.ANSIBLE_DIR}}"
    cmds:
      - "ansible-playbook -i inventories/proxmox -l {{.NET_LXC_HOST_FQDN}} upgrade22_to_24.yml"
      - "ansible-playbook -i inventories/proxmox {{.NET_LXC_ANSIBLE_PLAYBOOK}}"

  provision-tailscale:
    desc: "Provision 'Tailscale' on '{{.NET_LXC_HOST}}'"
    dir: "{{.ANSIBLE_DIR}}"
    cmds:
      - "ansible-playbook -i inventories/proxmox {{.NET_LXC_ANSIBLE_PLAYBOOK}} --tag tailscale"

  provision-rustdesk:
    desc: "Provision 'RustDesk' on '{{.NET_LXC_HOST}}'"
    dir: "{{.ANSIBLE_DIR}}"
    cmds:
      - "ansible-playbook -i inventories/proxmox {{.NET_LXC_ANSIBLE_PLAYBOOK}} --tag rustdesk"

