-
  type: markets
  title: crypto
  markets:
    -
      symbol: BTC-USD
      name: Bitcoin
    -
      symbol: ETH-USD
      name: Ethereum
    -
      symbol: SOL-USD
      name: Solana
    -
      symbol: ADA-USD
      name: Cardano
