-
  type: markets
  markets:
    -
      symbol: SPY
      name: S&P 500
    -
      symbol: AMZN
      name: Amazon
    -
      symbol: AAPL
      name: Apple
    -
      symbol: GOOGL
      name: Google
    -
      symbol: META
      name: Meta
    -
      symbol: MSFT
      name: Microsoft
    -
      symbol: NVDA
      name: NVIDIA
    -
      symbol: TSLA
      name: Tesla
