---
speedtest_tracker_directory: /opt/speedtest_tracker
speedtest_tracker_uri: speedtest-tracker.{{ global_domain }}
speedtest_tracker_port: 80

speedtest_app_key: "{{ lookup('ansible.builtin.ini', 'app_key', section='speedtest-tracker', file='credentials.ini') }}"
