---
backrest_directory: /opt/backrest
backrest_version: v1-scratch
backrest_port: 9898
backrest_uri: "backrest-{{ inventory_hostname_short }}.{{ global_domain }}"

backrest_prune_min: "{{ 59 | random(start=1) }}"
backrest_prune_hour: "{{ 23 | random(start=1) }}"
backrest_check_min: "{{ 59 | random(start=1) }}"
backrest_check_hour: "{{ 23 | random(start=1) }}"

backrest_guid: "{{ inventory_hostname_short | ansible.builtin.to_uuid | ansible.builtin.hash('sha256') }}"
backrest_password: "{{ lookup('ansible.builtin.ini', 'password', section='backrest', file='credentials.ini') }}"

telegram_bot_token: "{{ lookup('ansible.builtin.ini', 'bot_token', section='telegram', file='credentials.ini') }}"
telegram_chat_id: "{{ lookup('ansible.builtin.ini', 'chat_id', section='telegram', file='credentials.ini') }}"
