---
- name: Install Arr Stack
  block:

    - name: Create app directory
      ansible.builtin.file:
        path: "{{ arr_directory }}"
        state: directory
        mode: 0755

    - name: Create Arr* apps directory
      ansible.builtin.file:
        path: "{{ arr_apps_directory }}"
        state: directory
        owner: "{{ arr_puid }}"
        group: "{{ arr_pgid }}"
        mode: 0755

    - name: Copy docker-compose file
      ansible.builtin.template:
        src: docker-compose.yml.j2
        dest: "{{ arr_directory }}/docker-compose.yml"
        owner: root
        group: root
        mode: 0644

    - name: Create and start app
      community.docker.docker_compose_v2:
        project_src: "{{ arr_directory }}"
        recreate: always
        pull: missing
        remove_orphans: true
        remove_volumes: true
        state: restarted

  tags: arr_stack
