---
booklore_directory: /opt/booklore
booklore_uri: "booklore.{{ global_domain }}"
booklore_port: 6060
booklore_version: v1.14.1

booklore_db_username: "{{ lookup('ansible.builtin.ini', 'booklore_db_username', section='booklore', file='credentials.ini') }}"
booklore_db_password: "{{ lookup('ansible.builtin.ini', 'booklore_db_password', section='booklore', file='credentials.ini') }}"
booklore_db_name: "{{ lookup('ansible.builtin.ini', 'booklore_db_name', section='booklore', file='credentials.ini') }}"
