---
nfs_pkgs:
  - nfs-common

nfs_docker_path: /var/lib/docker/volumes
nfs_server: ds1.macminis.net:/volume1/proxmox
nfs_options: rw,relatime,vers=4.0,rsize=131072,wsize=131072,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,local_lock=none
