---
nfs_server: "ds1.{{ global_domain }}"
nfs_options_rw: rw,relatime,vers=4.0,rsize=131072,wsize=131072,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,local_lock=none,_netdev
nfs_options_ro: ro,relatime,vers=4.0,rsize=131072,wsize=131072,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,local_lock=none,_netdev

nfs_pkgs:
  - nfs-common

nfs_volumes:
  backups: /volume1/backups
  booklore: /volume1/booklore
  books: /volume1/books
  devbox: /volume1/devbox
  docker: /volume1/docker
  downloads: /volume1/downloads
  movies: /volume1/movies
  music: /volume1/music
  stash: /volume1/stash
  tv: /volume1/tv

nfs_client_mounts: []
