---
is_dockerized: false
is_subnet_router: false
is_cloudybox: false

tailscale_directory: /opt/tailscale
tailscale_routes: 192.168.136.0/24

tailscale_homelab_authkey: "{{ lookup('ansible.builtin.ini', 'homelab_auth_key', section='tailscale', file='credentials.ini') }}"
tailscale_cloudybox_authkey: "{{ lookup('ansible.builtin.ini', 'cloudybox_auth_key', section='tailscale', file='credentials.ini') }}"
tailscale_authkey: "{{ tailscale_cloudybox_authkey if is_cloudybox == true else tailscale_homelab_authkey }}"

# yamllint disable rule:line-length
tailscale_apt_gpg_key: "https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}.gpg"
tailscale_apt_repository: "deb https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} main"
