---
is_dockerized: false
is_subnet_router: false

tailscale_directory: /opt/tailscale
tailscale_authkey: "{{ lookup('ansible.builtin.ini', 'auth_key', section='tailscale-lxc', file='credentials.ini') }}"
tailscale_routes: 192.168.136.0/24

# yamllint disable rule:line-length
tailscale_apt_gpg_key: "https://pkgs.tailscale.com/stable/{{ ansible_distribution|lower }}/{{ ansible_distribution_release|lower }}.gpg"
tailscale_apt_repository: "deb https://pkgs.tailscale.com/stable/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }} main"
