---
is_agent: false
dozzle_agent_port: 7007

dozzle_directory: /opt/dozzle
dozzle_uri: dozzle.{{ global_domain }}
dozzle_server_port: 8080
dozzle_image_version: v8
dozzle_remote_agents:
  - arr-lxc.{{ global_domain }}:{{ dozzle_agent_port }}
  - cloudy-box.{{ global_domain }}:{{ dozzle_agent_port }}
  - devbox-lxc.{{ global_domain }}:{{ dozzle_agent_port }}
  - net-lxc.{{ global_domain }}:{{ dozzle_agent_port }}
  - rpi0.{{ global_domain }}:{{ dozzle_agent_port }}
  - rpi1.{{ global_domain }}:{{ dozzle_agent_port }}
