---
- name: Tailscale sysctl modifications
  ansible.builtin.copy:
    dest: /etc/sysctl.d/90-tailscale.conf
    content: |
      net.ipv4.ip_forward=1
      net.ipv6.conf.all.forwarding=1
    owner: root
    group: root
    mode: 0644
  register: tailscale_file

- name: run sysctl cmd
  ansible.builtin.command: sysctl --system
  when: tailscale_file is changed
