---
- name: Install termix
  block:

    - name: Create app directory
      ansible.builtin.file:
        path: "{{ termix_directory }}"
        state: directory
        mode: 0755

    - name: Copy docker-compose file
      ansible.builtin.template:
        src: docker-compose.yml.j2
        dest: "{{ termix_directory }}/docker-compose.yml"
        owner: root
        group: root
        mode: 0644

    - name: Create and start app
      community.docker.docker_compose_v2:
        project_src: "{{ termix_directory }}"

    - name: Wait until certificate is registered
      ansible.builtin.uri:
        url: "https://{{ termix_uri }}/"
        validate_certs: true
        status_code:
          - 200
      register: uri_output
      until: uri_output.status == 200
      delay: 10
      retries: 30       # Retries for 30 * 10 secs = 300 secs = 5 mins

  tags: termix
